apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-input-output
data:
  fluentd.conf: |-
    # Ignore fluentd own events
    <match fluent.**>
      @type null
    </match>

    @include fluentd-inputs.conf
    @include fluentd-output.conf
    # @include metrics.conf
  fluentd-inputs.conf: |-
    <source>
      @type forward
      @id fluentd_aggregator
      port 24224
      bind 0.0.0.0
      @label @OUTPUT
    </source>

    # HTTP input for the liveness and readiness probes
    <source>
      @type http
      bind 0.0.0.0
      port 9880
    </source>

  fluentd-output.conf: |-
    # Throw the healthcheck to the standard output instead of forwarding it
    <match fluentd.healthcheck>
      @type stdout
    </match>

    <label @OUTPUT>
      <match **>
        @type elasticsearch
        include_tag_key true
        host "#{ENV['ELASTICSEARCH_HOST']}"
        port "#{ENV['ELASTICSEARCH_PORT']}"
        user "#{ENV['FLUENTD_ELASTICSEARCH_USER']}"
        password "#{ENV['FLUENTD_ELASTICSEARCH_PASSWORD']}"
        scheme https
        path ""
        ssl_verify false
        # Don't wait for elastic to start up.
        verify_es_version_at_startup false
        default_elasticsearch_version 8
      </match>
    </label>
