## Forwarder parameters
##
forwarder:
  ## @param forwarder.enabled Enable forwarder daemonset
  ##
  enabled: false
## Aggregator parameters
##
aggregator:
  ## @param aggregator.enabled Enable Fluentd aggregator statefulset
  ##
  enabled: true
  ## @param aggregator.replicaCount Number of aggregator pods to deploy in the Stateful Set
  ##
  replicaCount: 1
  ## Pods Service Account
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
  ##
  configMap: fluentd-input-output
  ## @param aggregator.extraEnvVars Extra environment variables to pass to the container
  ## extraEnvVars:
  ##   - name: MY_ENV_VAR
  ##     value: my_value
  ##
  extraEnvVars:
    - name: ELASTICSEARCH_HOST
      value: "logging-elasticsearch"
    - name: ELASTICSEARCH_PORT
      value: "9200"

  ## @param aggregator.extraEnvVarsSecret Name of existing Secret containing extra env vars for Fluentd Aggregator nodes
  ##
  extraEnvVarsSecret: logging-fluentd
  ## Aggregator containers' resource requests and limits
  ## ref: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
  ## We usually recommend not to specify default resources and to leave this as a conscious
  ## choice for the user. This also increases chances charts run on environments with little
  ## resources, such as Minikube. If you do want to specify resources, uncomment the following
  ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  ## @param aggregator.resourcesPreset Set container resources according to one common preset (allowed values: none, nano, micro, small, medium, large, xlarge, 2xlarge). This is ignored if aggregator.resources is set (aggregator.resources is recommended for production).
  ## More information: https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15
  ##
  resourcesPreset: "nano"